name: Windows tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        python -m pip install torch==1.13.1 torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu117
        python -m pip install dgl==1.0.1 -f https://data.dgl.ai/wheels/repo.html
        python -m pip install dglgo -f https://data.dgl.ai/wheels-test/repo.html
        python -m pip install git+https://github.com/marcown/imgaug.git@74e63f2#egg=imgaug
        python -m pip install .
    - name: Test with pytest
      run: |
        pytest
